import type { CategoryDefinition, RegulationItem } from './types.js';

const SOLID_WASTE_LAW: RegulationItem = {
  title: '中华人民共和国固体废物污染环境防治法',
  authority: '全国人大常委会',
  referenceUrl: 'https://www.gov.cn/xinwen/2020-04/30/content_5507561.htm',
};

const RECYCLING_MEASURE: RegulationItem = {
  title: '再生资源回收管理办法',
  authority: '商务部',
  referenceUrl: 'https://www.gov.cn/gongbao/content/2007/content_721184.htm',
};

const HAZARDOUS_TRANSFER: RegulationItem = {
  title: '危险废物转移管理办法',
  authority: '生态环境部',
  referenceUrl: 'https://www.mee.gov.cn/xxgk2018/xxgk/xxgk02/202111/t20211130_962150.html',
};

export const COMMON_REGULATIONS: RegulationItem[] = [SOLID_WASTE_LAW, RECYCLING_MEASURE];

export const CITY_PRIORITY = '天津';

const CATEGORY_PAIN_POINTS: Record<string, string[]> = {
  'scrap-steel': [
    '钢厂到厂价、基地收购价和社会面流通价分层明显，单一报价难反映真实成交区间。',
    '轻薄料、压块料和工地料扣杂标准不一，验货后价差波动大。',
    '物流半径和装卸效率直接吞噬毛利，跨区域调货对时效和现金流要求高。',
  ],
  'scrap-copper': [
    '品位判定高度依赖现场拆解和经验，光亮铜、杂铜、黄铜之间的价差极易被误判。',
    '线缆剥离、损耗和税票处理影响最终净价，公开报价通常低于可落地成交价。',
    '国际铜价、汇率和下游铜杆订单联动紧，回收端容易出现高波动低锁价的问题。',
  ],
  'scrap-aluminum': [
    '生铝、熟铝、铝合金和铝屑的杂质控制标准差异大，来料一旦混级就会压价。',
    '除漆、除铁和熔损率直接决定利润，很多公开价格未体现加工损耗。',
    '再生铝下游需求受汽车、建筑和家电订单影响明显，回收端波动具有周期性。',
  ],
  'waste-plastic': [
    '同样是塑料，颜色、树脂牌号、洁净度和含水率都会让回收价产生明显分层。',
    '清洗、热洗、造粒能耗高，低端料在电价和人工上涨时容易出现倒挂。',
    '再生料销售受原油和新料价格挤压，公开回收价与终端成交价经常不同步。',
  ],
  'waste-paper': [
    'AA级、A级、统货和花纸边等级边界并不统一，纸厂扣点口径差异很大。',
    '纸厂调价频繁，回收站库存一旦压货，单日价差就可能迅速放大。',
    '含水率、杂质率和打包密度直接影响到厂结算，公开参考价不等于最终回款价。',
  ],
  'waste-glass': [
    '白料、青料和杂色料价格差异大，但前端分色回收难度高，常导致混级降价。',
    '运输成本在玻璃回收中占比偏高，低值料跨区域流动空间有限。',
    '下游窑炉和建材企业对粒径、洁净度要求高，分拣不达标会导致整车退货。',
  ],
  'power-battery': [
    '包级、模组级和黑粉级报价逻辑不同，公开价格往往只反映局部环节。',
    '安全放电、拆解资质和危废转运合规门槛高，回收端不是简单比吨价。',
    '镍钴锂价格波动会快速传导到电池回收端，库存和账期风险都比较高。',
  ],
  'scrapped-vehicle': [
    '整车收购价、五大总成残值和废钢残值叠加，定价模型比普通废钢复杂得多。',
    '注销、拆解、危废处理和零部件流向管理要求严格，合规成本高。',
    '拆解件流通节奏慢、占用场地大，现金回笼周期通常长于其他再生品类。',
  ],
  'e-waste': [
    '电子废弃物品类极杂，板卡、家电和通信设备的估值逻辑完全不同。',
    '贵金属回收价值高，但拆解和环保要求也高，非标准操作容易形成损耗。',
    '回收端普遍存在信息不透明问题，同品类因成色和型号不同价差极大。',
  ],
  'waste-textile': [
    '旧衣、棉布、化纤和工业边角料流向不同，混装会直接降低分拣价值。',
    '分拣人工依赖度高，成色和材质识别标准难完全标准化。',
    '可再穿戴流通、再生纤维和终端消纳渠道不稳定，导致库存周转慢。',
  ],
  'waste-rubber': [
    '废轮胎、胶块、橡胶粉和热解料价值链不同，前端回收很难统一计价。',
    '钢丝分离、纤维去除和粒径控制成本高，很多报价未反映加工深度差异。',
    '下游再生胶、改性料和燃料市场波动大，回收端利润空间易被压缩。',
  ],
  'waste-wood': [
    '木托盘、模板木和混合木料品质差异大，水分和含钉率直接影响成交价。',
    '前端拆钉、去杂和破碎成本高，低值木料很容易被物流吃掉利润。',
    '板材厂、生物质厂和园林终端需求并不稳定，价格弹性有限。',
  ],
  'kitchen-grease': [
    '餐厨废油和固形厨余回收逻辑不同，混收会影响精炼效率和结算口径。',
    '收运合规、台账管理和流向监管严格，回收商运营门槛高。',
    '油脂酸价、水分和杂质含量波动大，公开报价很难完全反映真实质量差异。',
  ],
  'industrial-slag': [
    '工业废渣危险属性和可利用属性需要先判断，不同来源处理路径差异大。',
    '检测、稳定化和资源化加工投入高，价格不仅看吨位还看处置难度。',
    '终端消纳依赖建材和道路工程项目，需求释放往往带有明显项目周期。',
  ],
  'municipal-solid-waste': [
    '生活垃圾中的可回收物价值被分拣效率决定，前端分类质量直接影响回收价。',
    '低值可回收物运费和人工占比高，很多场景只能靠规模化摊薄成本。',
    '各城市分类标准和回收体系差异大，全国价格参考的可比性并不强。',
  ],
  'construction-waste': [
    '建筑垃圾含土率、轻物质比例和粒径差异大，再生骨料定价标准不完全统一。',
    '现场分类不到位会抬高后端破碎筛分成本，直接压缩处置利润。',
    '再生骨料终端接受度和项目招标政策密切相关，价格受政策驱动明显。',
  ],
};

const BASE_RECYCLING_CATEGORIES: Array<Omit<CategoryDefinition, 'painPoints'>> = [
  {
    id: 'scrap-steel',
    name: '废钢',
    subcategories: ['重废', '中废', '轻薄料', '钢筋压块', '工地料'],
    searchKeyword: '废钢 回收',
    quoteKeywords: ['废钢', '废铁', '钢筋头', '钢板边角料', '工地料', '重废'],
    newsKeywordsCn: ['废钢', '废铁', '钢厂调价', '螺纹', '钢材'],
    newsKeywordsEn: ['scrap steel', 'ferrous scrap', 'steel recycling'],
    costStructure: [
      { label: '收购价', percent: 72 },
      { label: '分拣与加工', percent: 10 },
      { label: '运输', percent: 12 },
      { label: '损耗与管理', percent: 6 },
    ],
    processFlow: [
      { step: 1, title: '回收集货', description: '回收站按重废、中废、轻薄料分级收货。' },
      { step: 2, title: '预处理', description: '去杂、剪切、打包，形成钢厂可接收料型。' },
      { step: 3, title: '物流进厂', description: '按到厂标准过磅、质检、扣杂。' },
      { step: 4, title: '熔炼再生', description: '进入电炉/转炉配料，形成再生钢原料。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'scrap-copper',
    name: '废铜',
    subcategories: ['1#光亮铜', '2#铜', '黄铜', '铜米', '杂铜'],
    searchKeyword: '废铜 回收',
    quoteKeywords: ['废铜', '紫铜', '黄铜', '铜米', '电缆铜'],
    newsKeywordsCn: ['废铜', '铜价', '铜杆', '再生铜'],
    newsKeywordsEn: ['scrap copper', 'copper recycling', 'copper scrap'],
    costStructure: [
      { label: '收购价', percent: 78 },
      { label: '拆解剥离', percent: 9 },
      { label: '运输', percent: 8 },
      { label: '损耗与税费', percent: 5 },
    ],
    processFlow: [
      { step: 1, title: '分选定级', description: '按光亮铜、杂铜、黄铜等品级分流。' },
      { step: 2, title: '破碎剥离', description: '电缆线类进行破碎与物理分选。' },
      { step: 3, title: '精炼处理', description: '除杂后进入再生铜冶炼环节。' },
      { step: 4, title: '再生利用', description: '输出再生铜杆、铜锭等产品。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'scrap-aluminum',
    name: '废铝',
    subcategories: ['机生铝', '熟铝', '铝合金', '易拉罐铝', '铝屑'],
    searchKeyword: '废铝 回收',
    quoteKeywords: ['废铝', '工业铝', '铝合金', '生铝', '熟铝', '铝屑'],
    newsKeywordsCn: ['废铝', '铝价', '再生铝'],
    newsKeywordsEn: ['scrap aluminum', 'aluminium recycling', 'secondary aluminum'],
    costStructure: [
      { label: '收购价', percent: 75 },
      { label: '预处理', percent: 11 },
      { label: '运输', percent: 9 },
      { label: '能耗与管理', percent: 5 },
    ],
    processFlow: [
      { step: 1, title: '来料验级', description: '按型材、压铸、易拉罐等类别收料。' },
      { step: 2, title: '破碎除杂', description: '去漆、去铁及杂质分离。' },
      { step: 3, title: '熔炼合金化', description: '按牌号进行配比熔炼。' },
      { step: 4, title: '铸锭/再加工', description: '形成再生铝锭和再加工材料。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'waste-plastic',
    name: '废塑料',
    subcategories: ['PET瓶片', 'PP再生料', 'PE再生料', 'ABS再生料', '混合塑料'],
    searchKeyword: '废塑料 回收',
    quoteKeywords: ['废塑料', '再生塑料', '塑料', 'PET', 'PP', 'PE', 'ABS', '瓶片'],
    newsKeywordsCn: ['废塑料', '再生塑料', '瓶片', '再生料'],
    newsKeywordsEn: ['waste plastic', 'plastic recycling', 'recycled polymer'],
    costStructure: [
      { label: '收购价', percent: 62 },
      { label: '清洗分选', percent: 16 },
      { label: '造粒加工', percent: 14 },
      { label: '物流与损耗', percent: 8 },
    ],
    processFlow: [
      { step: 1, title: '分类收集', description: '按树脂种类和颜色进行分拣。' },
      { step: 2, title: '清洗破碎', description: '去标、去杂、破碎和热洗。' },
      { step: 3, title: '熔融造粒', description: '挤出、过滤、切粒形成再生颗粒。' },
      { step: 4, title: '改性应用', description: '按下游要求进行改性与配方调整。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'waste-paper',
    name: '废纸',
    subcategories: ['AA级', 'A级', 'B级', '统货', '花纸边'],
    searchKeyword: '废纸 回收',
    quoteKeywords: ['废纸', '黄板纸', '箱板纸', '书本纸', '纸浆'],
    newsKeywordsCn: ['废纸', '纸厂调价', '黄板纸', '再生纸'],
    newsKeywordsEn: ['waste paper', 'recovered paper', 'paper recycling'],
    costStructure: [
      { label: '收购价', percent: 68 },
      { label: '打包分拣', percent: 12 },
      { label: '物流', percent: 13 },
      { label: '损耗与管理', percent: 7 },
    ],
    processFlow: [
      { step: 1, title: '回收分类', description: '按黄板纸、白纸、报纸等等级分类。' },
      { step: 2, title: '打包运输', description: '压包后进入纸厂到厂体系。' },
      { step: 3, title: '制浆脱墨', description: '碎解、筛选、净化形成再生浆。' },
      { step: 4, title: '抄纸成品', description: '进入瓦楞、箱板等纸机生产线。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'waste-glass',
    name: '废玻璃',
    subcategories: ['白料', '青料', '杂色料', '平板玻璃', '玻璃瓶片'],
    searchKeyword: '废玻璃 回收',
    quoteKeywords: ['废玻璃', '玻璃瓶', '碎玻璃', '平板玻璃'],
    newsKeywordsCn: ['废玻璃', '玻璃回收', '再生玻璃'],
    newsKeywordsEn: ['waste glass', 'cullet', 'glass recycling'],
    costStructure: [
      { label: '收购价', percent: 55 },
      { label: '分色分拣', percent: 18 },
      { label: '破碎清洗', percent: 17 },
      { label: '运输', percent: 10 },
    ],
    processFlow: [
      { step: 1, title: '分色回收', description: '按白料、青料、杂色玻璃分选。' },
      { step: 2, title: '除杂破碎', description: '去金属、标签与杂质后破碎。' },
      { step: 3, title: '粒度控制', description: '筛分后形成稳定粒径玻璃砂。' },
      { step: 4, title: '再熔利用', description: '回到玻璃窑炉或建材体系。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'power-battery',
    name: '动力电池',
    subcategories: ['磷酸铁锂电池', '三元电池', '模组', '电池黑粉', '电芯壳体'],
    searchKeyword: '动力电池 回收',
    quoteKeywords: ['动力电池', '锂电池', '电池回收', '磷酸铁锂', '三元电池', '黑粉'],
    newsKeywordsCn: ['动力电池', '梯次利用', '电池回收', '电池拆解'],
    newsKeywordsEn: ['power battery recycling', 'lithium battery recycling', 'black mass'],
    costStructure: [
      { label: '收购价', percent: 64 },
      { label: '拆解与放电', percent: 14 },
      { label: '湿法/火法提取', percent: 17 },
      { label: '环保与合规', percent: 5 },
    ],
    processFlow: [
      { step: 1, title: '回收与溯源', description: '按编码追溯来源并做安全入库。' },
      { step: 2, title: '拆解放电', description: '包级/模组级拆解并进行安全放电。' },
      { step: 3, title: '材料提取', description: '通过物理分选与湿法提取有价金属。' },
      { step: 4, title: '梯次或再生', description: '可用电芯梯次利用，其余再生冶炼。' },
    ],
    regulations: [
      SOLID_WASTE_LAW,
      {
        title: '新能源汽车动力蓄电池回收利用管理暂行办法',
        authority: '工信部等七部委',
        referenceUrl: 'https://www.gov.cn/xinwen/2018-02/26/content_5268846.htm',
      },
      HAZARDOUS_TRANSFER,
    ],
  },
  {
    id: 'scrapped-vehicle',
    name: '报废汽车',
    subcategories: ['整车回收', '发动机总成', '前后桥', '车身钢料', '拆车件'],
    searchKeyword: '报废汽车 回收',
    quoteKeywords: ['报废汽车', '报废机动车', '拆车件', '汽车拆解'],
    newsKeywordsCn: ['报废汽车', '报废机动车', '汽车拆解'],
    newsKeywordsEn: ['end-of-life vehicle', 'vehicle dismantling', 'auto recycling'],
    costStructure: [
      { label: '收购价', percent: 70 },
      { label: '拆解工时', percent: 11 },
      { label: '零部件处理', percent: 11 },
      { label: '环保合规', percent: 8 },
    ],
    processFlow: [
      { step: 1, title: '回收登记', description: '车辆注销、验车并完成回收登记。' },
      { step: 2, title: '预处理', description: '排液、拆除危废部件和气囊等。' },
      { step: 3, title: '精细拆解', description: '分类拆件，金属与可用件分流。' },
      { step: 4, title: '资源化利用', description: '钢铁/有色入炉，再制造件流通。' },
    ],
    regulations: [
      SOLID_WASTE_LAW,
      {
        title: '报废机动车回收管理办法',
        authority: '国务院',
        referenceUrl: 'https://www.gov.cn/zhengce/content/2019-05/06/content_5389987.htm',
      },
      RECYCLING_MEASURE,
    ],
  },
  {
    id: 'e-waste',
    name: '电子废弃物',
    subcategories: ['废电路板', '废旧家电', '旧电脑', '旧手机', '电子元件混合料'],
    searchKeyword: '电子废弃物 回收',
    quoteKeywords: ['电子废弃物', '废旧电子', '废旧家电', '线路板', '废电路板', '旧电脑', '旧手机', '电子料'],
    newsKeywordsCn: ['电子废弃物', '废家电', '线路板', '拆解'],
    newsKeywordsEn: ['e-waste', 'waste electronics', 'pcb recycling'],
    costStructure: [
      { label: '收购价', percent: 58 },
      { label: '拆解分选', percent: 18 },
      { label: '金属提炼', percent: 16 },
      { label: '危废处理', percent: 8 },
    ],
    processFlow: [
      { step: 1, title: '分类收运', description: '按家电、通讯、板卡等门类收集。' },
      { step: 2, title: '人工拆解', description: '拆下高价值元器件与危险部件。' },
      { step: 3, title: '破碎分选', description: '磁选、涡电流和密度分选金属。' },
      { step: 4, title: '冶炼再生', description: '贵金属、有色金属进入再生链条。' },
    ],
    regulations: [
      SOLID_WASTE_LAW,
      {
        title: '废弃电器电子产品回收处理管理条例',
        authority: '国务院',
        referenceUrl: 'https://www.gov.cn/zwgk/2011-02/25/content_1815473.htm',
      },
      HAZARDOUS_TRANSFER,
    ],
  },
  {
    id: 'waste-textile',
    name: '废旧纺织品',
    subcategories: ['旧衣', '棉布料', '化纤料', '牛仔料', '毛纺料'],
    searchKeyword: '废旧纺织品 回收',
    quoteKeywords: ['废旧纺织品', '旧衣服', '旧衣', '废布料', '纺织下脚料'],
    newsKeywordsCn: ['废旧纺织品', '旧衣回收', '纺织回收'],
    newsKeywordsEn: ['textile recycling', 'used clothing', 'fabric waste'],
    costStructure: [
      { label: '收购价', percent: 60 },
      { label: '分拣人工', percent: 20 },
      { label: '清洗/消毒', percent: 12 },
      { label: '物流', percent: 8 },
    ],
    processFlow: [
      { step: 1, title: '前端回收', description: '社区与企业端旧纺织品集中收集。' },
      { step: 2, title: '分级分拣', description: '按成色、材质与用途进行分级。' },
      { step: 3, title: '再制造', description: '可穿戴品复用，不可穿戴品开松再生。' },
      { step: 4, title: '终端利用', description: '进入再生纤维、保温材料等场景。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'waste-rubber',
    name: '废橡胶',
    subcategories: ['废轮胎', '橡胶块', '橡胶粉', '丁基胶', '三元乙丙胶'],
    searchKeyword: '废橡胶 回收',
    quoteKeywords: ['废橡胶', '废轮胎', '轮胎', '橡胶粉', '胶块'],
    newsKeywordsCn: ['废橡胶', '废轮胎', '再生胶'],
    newsKeywordsEn: ['scrap rubber', 'tire recycling', 'crumb rubber'],
    costStructure: [
      { label: '收购价', percent: 63 },
      { label: '切块钢丝分离', percent: 16 },
      { label: '粉碎与筛分', percent: 14 },
      { label: '物流', percent: 7 },
    ],
    processFlow: [
      { step: 1, title: '回收集货', description: '轮胎和橡胶边角料分类收运。' },
      { step: 2, title: '预处理', description: '切块并进行钢丝和纤维分离。' },
      { step: 3, title: '深加工', description: '制备橡胶粉、再生胶或热解料。' },
      { step: 4, title: '下游应用', description: '路面材料、橡胶制品与燃料利用。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'waste-wood',
    name: '废木材',
    subcategories: ['废木托盘', '模板木', '锯末', '木片', '混合木料'],
    searchKeyword: '废木材 回收',
    quoteKeywords: ['废木材', '木托盘', '木方', '废旧木料'],
    newsKeywordsCn: ['废木材', '木托盘回收', '生物质'],
    newsKeywordsEn: ['waste wood', 'wood recycling', 'biomass waste'],
    costStructure: [
      { label: '收购价', percent: 58 },
      { label: '拆钉分选', percent: 17 },
      { label: '破碎加工', percent: 17 },
      { label: '运输', percent: 8 },
    ],
    processFlow: [
      { step: 1, title: '拆解分类', description: '托盘、模板、家具木料分类。' },
      { step: 2, title: '除杂预处理', description: '去钉去杂，控制含水率。' },
      { step: 3, title: '破碎成料', description: '制备木片、木粉或压块。' },
      { step: 4, title: '资源化利用', description: '用于板材、燃料和园林覆盖物。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'kitchen-grease',
    name: '厨余/油脂',
    subcategories: ['餐厨废油', '地沟油', '潲水油', '油脂残渣', '餐厨固形物'],
    searchKeyword: '废油脂 回收',
    quoteKeywords: ['厨余', '餐厨废油', '地沟油', '废油脂', '餐厨垃圾', '废食用油', '废油'],
    newsKeywordsCn: ['厨余', '餐厨垃圾', '废油脂', '生物柴油'],
    newsKeywordsEn: ['used cooking oil', 'kitchen waste', 'biodiesel feedstock'],
    costStructure: [
      { label: '收购价', percent: 61 },
      { label: '收运', percent: 15 },
      { label: '预处理提纯', percent: 17 },
      { label: '环保合规', percent: 7 },
    ],
    processFlow: [
      { step: 1, title: '定点回收', description: '餐饮端定点收运和台账管理。' },
      { step: 2, title: '固液分离', description: '去渣、脱水、酸价调节。' },
      { step: 3, title: '精炼转化', description: '制备工业级油脂或生物柴油原料。' },
      { step: 4, title: '终端利用', description: '进入生物燃料和化工体系。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'industrial-slag',
    name: '工业废渣',
    subcategories: ['钢渣', '高炉矿渣', '粉煤灰', '有色冶炼渣', '炉底渣'],
    searchKeyword: '工业废渣 回收',
    quoteKeywords: ['工业废渣', '钢渣', '矿渣', '炉渣', '粉煤灰'],
    newsKeywordsCn: ['工业废渣', '钢渣', '粉煤灰', '固废资源化'],
    newsKeywordsEn: ['industrial slag', 'ash recycling', 'solid waste utilization'],
    costStructure: [
      { label: '收购价', percent: 57 },
      { label: '检测与分级', percent: 15 },
      { label: '破碎筛分', percent: 18 },
      { label: '运输', percent: 10 },
    ],
    processFlow: [
      { step: 1, title: '来源核验', description: '核验来源与危险属性判定。' },
      { step: 2, title: '分级处理', description: '按组分和活性进行分级。' },
      { step: 3, title: '加工改性', description: '破碎、筛分、稳定化处理。' },
      { step: 4, title: '建材利用', description: '进入水泥掺合料和道路材料。' },
    ],
    regulations: [SOLID_WASTE_LAW, HAZARDOUS_TRANSFER, RECYCLING_MEASURE],
  },
  {
    id: 'municipal-solid-waste',
    name: '生活垃圾',
    subcategories: ['可回收纸类', '可回收塑料', '可回收金属', '玻璃可回收物', '其他可回收物'],
    searchKeyword: '生活垃圾 回收',
    quoteKeywords: ['生活垃圾', '可回收物', '垃圾分拣', '再生资源分拣'],
    newsKeywordsCn: ['生活垃圾', '垃圾分类', '可回收物'],
    newsKeywordsEn: ['municipal solid waste', 'recyclables sorting', 'waste sorting'],
    costStructure: [
      { label: '分拣后回收价', percent: 54 },
      { label: '分拣人工', percent: 22 },
      { label: '运输', percent: 14 },
      { label: '场站运营', percent: 10 },
    ],
    processFlow: [
      { step: 1, title: '分类投放', description: '居民端完成四分类或多分类投放。' },
      { step: 2, title: '中转分拣', description: '分拣中心提取可回收物。' },
      { step: 3, title: '资源化处理', description: '金属、塑料、纸类进入再生链条。' },
      { step: 4, title: '闭环去向', description: '不可回收部分焚烧或填埋处置。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
  {
    id: 'construction-waste',
    name: '建筑废弃物',
    subcategories: ['混凝土块', '砖瓦料', '沥青料', '木质装修料', '轻质混合料'],
    searchKeyword: '建筑废弃物 回收',
    quoteKeywords: ['建筑废弃物', '建筑垃圾', '拆除料', '再生骨料'],
    newsKeywordsCn: ['建筑废弃物', '建筑垃圾', '再生骨料'],
    newsKeywordsEn: ['construction waste', 'demolition waste', 'recycled aggregates'],
    costStructure: [
      { label: '收购价', percent: 50 },
      { label: '分拣破碎', percent: 24 },
      { label: '运输', percent: 16 },
      { label: '场站与设备', percent: 10 },
    ],
    processFlow: [
      { step: 1, title: '现场分类', description: '拆除现场进行土、砖、混凝土分离。' },
      { step: 2, title: '破碎筛分', description: '多级破碎形成再生骨料粒级。' },
      { step: 3, title: '杂质剔除', description: '去除木材、塑料和轻质杂物。' },
      { step: 4, title: '再生应用', description: '用于垫层、再生砖和道路基层。' },
    ],
    regulations: [SOLID_WASTE_LAW, RECYCLING_MEASURE, HAZARDOUS_TRANSFER],
  },
];

export const RECYCLING_CATEGORIES: CategoryDefinition[] = BASE_RECYCLING_CATEGORIES.map((category) => ({
  ...category,
  painPoints: CATEGORY_PAIN_POINTS[category.id] ?? [
    '前端报价口径不统一，公开信息与现场成交存在偏差。',
    '物流、分拣和合规成本会持续影响净回收价。',
    '下游需求波动会快速传导到回收端利润。',
  ],
}));
